from hello import chai

chai("ginger tea")


#  AFTER EXECUTING THIS FILE, THE FUNCTION 'chai' IS IMPORTED FROM 'hello.py'
#  AND CALLED WITH THE ARGUMENT "ginger tea", PRINTING "ginger tea" TO THE CONSOLE.
#  THIS DEMONSTRATES HOW TO IMPORT AND USE FUNCTIONS FROM OTHER PYTHON FILES.
#  AND THE __PYCACHE__ FILE IS CREATED TO STORE BYTECODE FOR FASTER LOADING IN FUTURE EXECUTIONS.
#  THE IMPORT STATEMENT 'from hello import chai' ALLOWS US TO USE THE 'chai' FUNCTION
#  DEFINED IN 'hello.py' WITHOUT HAVING TO REDEFINE IT IN THIS FILE.
#  THIS IS A COMMON PRACTICE IN PYTHON TO ORGANIZE CODE AND REUSE FUNCTIONS ACROSS DIFFERENT SCRIPTS.
#  THE OUTPUT OF THIS CODE WILL BE:
#  ginger tea